name: 🚀　Release
on:
  push:
    branches:
      - master
      - next
      - next-major
      - alpha
      - beta
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/rsw-a/.github/workflows/release@master
