name: 🚀　Release
on:
  push:
    branches:
      - master
      - next
      - next-major
      - alpha
      - beta
jobs:
  run:
    uses: bubkoo/reusable-workflows/.github/workflows/semantic-release@master

