name: 🚀　Release
on:
  push:
    branches:
      - master
      - next
      - next-major
      - alpha
      - beta
jobs:
  run:
    uses: bubkoo/reusable-workflows/.github/workflows/semantic-release.yml@master
    with:
      extends: false
    secrets:
      app-id: ${{ secrets.APP_ID }}
      private-key: ${{ secrets.PRIVATE_KEY }}
      npm-token: ${{ secrets.NPM_TOKEN }}
